# Application config
application:
  integration:
    delivery-service:
      url: "http://localhost:8081"
      basepath: "/api/v1/delivery"
# Spring config
spring:
  application:
    name: order-service
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret

# Resilience4j config
resilience4j:
  circuitbreaker:
    instances:
      deliveryService:
        sliding-window-type: count_based
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
      rabbit-mq-circuit-breaker:
        sliding-window-type: count_based
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
    circuit-breaker-aspect-order: 1
  retry:
    instances:
      deliveryService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
      rabbit-mq-retry:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
    retry-aspect-order: 2
  ratelimiter:
    instances:
      httpController:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms

